/**
 * Tinkú — Strings es-AR (rioplatense).
 * Fuente única de texto visible al usuario. Facilita i18n futura sin refactor.
 * "vos" no "tú", "querés" no "quieres", celebraciones cálidas.
 */

export const strings = {
  common: {
    appName: 'Tinkú',
    tagline: 'Las Islas del Saber',
    loading: 'Cargando…',
    error: '¡Uy! Algo no salió bien. Probá de nuevo en un ratito.',
    retry: 'Reintentar',
    cancel: 'Cancelar',
    continue: 'Continuar',
    save: 'Guardar',
    back: 'Volver',
  },

  marketing: {
    heroTitle: 'Aprender jugando, de verdad.',
    heroSub: 'Tinkú acompaña a tus hijos a descubrir matemática y lengua en un mundo de islas, con contenido del currículo argentino y datos reales para vos.',
    ctaSignup: 'Crear cuenta gratis',
    ctaLogin: 'Ya tengo cuenta',
  },

  auth: {
    common: {
      continueGoogle: 'Continuar con Google',
      signupGoogle: 'Registrarse con Google',
      or: 'o',
    },
    signup: {
      title: 'Creá tu cuenta de padre/madre',
      subtitle: 'Necesitamos tus datos para configurar la cuenta. Los datos de tu hijo/a los vamos a pedir después, con tu consentimiento explícito.',
      fullNameLabel: 'Tu nombre y apellido',
      fullNamePlaceholder: 'Ej: Laura Martínez',
      emailLabel: 'Tu email',
      emailPlaceholder: 'laura@ejemplo.com',
      passwordLabel: 'Contraseña',
      passwordHelp: 'Mínimo 8 caracteres, al menos una letra y un número.',
      passwordPlaceholder: '••••••••',
      submit: 'Crear cuenta',
      submitting: 'Creando tu cuenta…',
      loginHint: '¿Ya tenés cuenta?',
      loginLink: 'Entrar',
      termsHint: 'Al crear tu cuenta aceptás los términos de uso y la política de privacidad.',
      errors: {
        emailTaken: 'Este email ya tiene una cuenta. ¿Querés entrar?',
        weakPassword: 'La contraseña es muy corta. Necesita mínimo 8 caracteres con letras y números.',
        invalidEmail: 'Ese email no parece válido.',
        generic: 'No pudimos crear la cuenta. Probá de nuevo en un momento.',
      },
    },
    login: {
      title: 'Entrar a Tinkú',
      subtitle: 'Accedé con tu email y contraseña.',
      emailLabel: 'Email',
      passwordLabel: 'Contraseña',
      submit: 'Entrar',
      submitting: 'Entrando…',
      signupHint: '¿Todavía no tenés cuenta?',
      signupLink: 'Crear cuenta',
      errors: {
        invalidCredentials: 'El email o la contraseña no coinciden.',
        rateLimited: 'Muchos intentos fallidos. Esperá unos minutos.',
        generic: 'No pudimos entrar. Probá de nuevo en un momento.',
      },
    },
    verify: {
      sentTitle: 'Revisá tu email',
      sentBody: 'Te mandamos un link a {email} para confirmar tu cuenta. Hacé click ahí y volvemos.',
      resend: 'Reenviar email',
      resending: 'Enviando…',
      resent: 'Listo, volvemos a mandarlo.',
      successTitle: '¡Email confirmado!',
      successBody: 'Ya podés empezar a usar Tinkú.',
      successCta: 'Ir al panel',
      invalidTitle: 'Link inválido o vencido',
      invalidBody: 'Este link ya se usó o se venció. Pedí uno nuevo desde tu panel.',
      invalidCta: 'Pedir nuevo link',
    },
  },

  parent: {
    dashboard: {
      title: 'Tu panel',
      welcome: '¡Hola, {name}!',
      verifyBanner: 'Te falta confirmar tu email. Revisá tu bandeja de entrada.',
      verifyBannerAction: 'Reenviar',
      noStudents: 'Todavía no agregaste hijos/as.',
      noStudentsCta: 'Agregar un hijo/a',
      addMoreCta: 'Agregar otro hijo/a',
      planLimitReached: 'Llegaste al límite de tu plan ({limit} hijo{s}). Actualizá a Premium para sumar más.',
      studentLoginCodeLabel: 'Código de ingreso',
      plan: {
        free: 'Plan gratuito',
        premiumActive: 'Plan Premium',
      },
    },
    students: {
      newTitle: 'Agregar un hijo/a',
      newSubtitle: 'Completá los datos y aceptá el consentimiento. Podés usar un apodo — no necesitamos el nombre completo.',
      firstNameLabel: 'Nombre o apodo',
      firstNamePlaceholder: 'Ej: Mateo, Lucha, Juani',
      birthYearLabel: 'Año de nacimiento',
      gradeLabel: 'Grado actual',
      gradeOption: { grade_1: '1° grado', grade_2: '2° grado', grade_3: '3° grado' },
      avatarLabel: 'Elegí un avatar',
      consentTitle: 'Consentimiento parental',
      consentAcceptLabel: 'Leí y acepto el consentimiento. Doy autorización explícita como tutor/a para que Tinkú procese los datos de mi hijo/a conforme a este texto.',
      submit: 'Crear cuenta del chico/a',
      submitting: 'Creando…',
      limitReachedTitle: 'No podés agregar otro hijo/a todavía',
      limitReachedBody: 'Tu plan actual permite hasta {limit} hijo{s}. Si querés sumar más, actualizá a Premium.',
      limitReachedCta: 'Ver planes',
      detail: {
        loginCodeHint: 'Tu hijo/a usa este código para entrar a Tinkú.',
        copyCode: 'Copiar código',
        copied: '¡Copiado!',
        regen: 'Regenerar código',
        regenConfirm: '¿Seguro? El código anterior deja de funcionar.',
        edit: 'Editar datos',
        requestDelete: 'Dar de baja este alumno/a',
        requestDeleteConfirm: '¿Estás seguro? Tu hijo/a pierde acceso inmediato. Tenés 30 días para arrepentirte antes de que los datos se borren definitivamente.',
        pendingDeletionTitle: 'Baja pendiente',
        pendingDeletionBody: 'Pediste dar de baja a este alumno/a. Los datos se anonimizan en 30 días. Podés cancelar antes.',
        cancelDeletion: 'Cancelar baja',
      },
      editTitle: 'Editar datos de {name}',
      errors: {
        planLimit: 'Llegaste al límite de tu plan. Para agregar más hijos, actualizá a Premium.',
        notFound: 'Alumno/a no encontrado.',
        validation: 'Revisá los campos marcados.',
        consentRequired: 'Tenés que aceptar el consentimiento para continuar.',
        generic: 'No pudimos guardar los cambios. Probá de nuevo.',
      },
    },
  },

  student: {
    entrar: {
      title: '¡Hola! Entrá a Tinkú',
      subtitle: 'Escribí tu código para empezar.',
      codeLabel: 'Tu código',
      codePlaceholder: 'KX3P9M',
      help: '¿No te anda? Pedile el código a tu mamá, papá o tutor.',
      submit: '¡Entrar!',
      submitting: 'Entrando…',
      errors: {
        invalidFormat: 'El código tiene 6 letras y números.',
        invalidCode: 'Mmm, ese código no funciona. Pedile ayuda a un adulto.',
        rateLimited: 'Probaste muchas veces. Esperá un ratito y volvé a intentar.',
        generic: '¡Uy! Algo no salió bien. Probá de nuevo en un momento.',
      },
    },
    islas: {
      title: 'Las Islas del Saber',
      subtitle: '¿A qué isla querés ir hoy, {name}?',
      comingSoon: 'Próximamente',
      salir: 'Salir',
      islands: {
        math: { name: 'Isla de los Números' },
        language: { name: 'Isla de las Palabras' },
        science: { name: 'Isla de la Naturaleza' },
        social: { name: 'Isla del Tiempo' },
        tech: { name: 'Isla de los Inventos' },
      },
    },
    islaNumeros: {
      title: 'Isla de los Números',
      subtitle: 'Acá vas a aprender Matemática como en una aventura.',
      comingSoonTitle: '¡Muy pronto!',
      comingSoonBody: 'Los primeros ejercicios están llegando. Volvé en un ratito.',
      back: '← Volver a las islas',
    },
    celebration: {
      masteredTitle: '¡Dominaste este concepto!',
      masteredBody: 'Qué fiera. Ya conocés esto al dedillo.',
      masteredCta: 'A otra actividad',
      badgeTitle: '¡Conseguiste una medalla!',
      badgeBody: 'Sumate la nueva a tu colección.',
      badgeCta: '¡Dale!',
      xpTitle: '¡Genial!',
      xpCta: '¡Seguir!',
    },
    logros: {
      navLink: 'Mis medallas',
    },
    dailyReview: {
      pill: 'REPASO DIARIO · 5 MIN',
      cardTitle: '¡Tu repaso de hoy te espera!',
      cardBody: '5 ejercicios cortitos para no olvidarte lo que aprendiste.',
      doneCardTitle: 'Ya hiciste tu repaso de hoy 🎯',
      doneCardBody: 'Seguí practicando lo que más te guste o volvé mañana.',
      progressLabel: 'Ejercicio {idx} de {total}',
      completeTitle: '¡Repaso completo!',
      completeBody: 'Respondiste {correct} de {total}. Seguí así, {studentName}.',
      completeCta: '¡A otra actividad!',
      firstBadgeTitle: '¡Tu primera medalla de repaso!',
      firstBadgeBody: 'Ganaste la medalla "Repaso del día". Volvé mañana por otra.',
      streakBadgeTitle: '¡Nueva racha desbloqueada!',
      streakBadgeBody: 'Cuantos más días seguidos, más grande la medalla.',
    },
  },
} as const;

export type Strings = typeof strings;
